apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-${BUILD_NUMBER}
spec:
  template:
    spec:
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:debug
          args:
            # 이전 설정의 Registry, Dockerfile 경로 반영
            - "--context=git://github.com/gorotis11/my-resume.git#refs/heads/${GIT_BRANCH}"
            - "--dockerfile=docker/Dockerfile"
            - "--destination=local-registry.registry.svc.cluster.local:443/my-resume:${BUILD_NUMBER}"
            - "--skip-tls-verify"
            - "--insecure"
            - "--cache=true"
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
      restartPolicy: Never
  backoffLimit: 0