apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-t1
spec:
  template:
    spec:
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:debug
          args:
            - "--context=git://github.com/gorotis11/my-resume.git#refs/heads/dev"
            - "--dockerfile=docker/Dockerfile"
            - "--destination=local-registry.registry.svc.cluster.local:443/my-resume:t1"
            - "--skip-tls-verify"
            - "--insecure"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi" # 메모리 부족으로 인한 OOM 방지
      restartPolicy: Never
  backoffLimit: 0