services:
    my-resume:
        image: my-resume:latest
        container_name: my-resume
        environment:
            - SERVICE_NAME=my-resume
            - SERVICE_VERSION=1.0.0
        expose:
            - 8080
        restart: always