version: "3"

services:
    my-resume:
        image: 192.168.45.100:5000/my-resume:${SERVICE_VERSION}
        container_name: my-resume
        environment:
            - SERVICE_NAME=${SERVICE_NAME}
            - SERVICE_VERSION=${SERVICE_VERSION}
            - DOCKER_HOST_NON_SECURE_PORT=${DOCKER_HOST_NON_SECURE_PORT}
        networks:
            - my-bridge-network
        ports:
            - ${DOCKER_HOST_NON_SECURE_PORT}:18080
        restart: always
networks:
    my-bridge-network:
        external: true