version: "3"

services:
    my-daily-reporter:
        image: gorotis11/my-resume:latest
        container_name: my-resume
        networks:
            - my-bridge-network
        ports:
            - 18080:18080
        restart: always
networks:
    my-bridge-network:
        external: true